### ISSUE TITLE
User lookup is failing with exception org.jose4j.lang.UnresolvableKeyException

### ISSUE THREAD

**Issue by phanitnm** [jenkinsci/azure-ad-plugin#201] opened 2022-05-06 20:51 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.332.3
Image : jenkins/jenkins:2.332.3-lts-jdk11
OS: Linux - 5.4.176-91.338.amzn2.x86_64
azure-ad:195.v8555a0bf0d22
Environment - AWS EKS Cluster
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller AWS EKS Cluster - Linux jenkins-tnm-0 5.4.176-91.338.amzn2.x86_64 #1 SMP Fri Feb 4 16:59:59 UTC 2022 x86_64 GNU/Linux

### Reproduction steps

1. Install Azure AD Plugin
2. Configured Security Realm - Verify application is successful.
3. Under Azure Active Directory Matrix-based security - Azure User/group to add - lookup a valid user in AD.

### Expected Results

AD User lookup should be successful and be able to add user to Azure AD matrix authorization.

### Actual Results

AD user lookup is failing with following exception -

2022-05-05 21:36:07.999+0000 [id=15]	WARNING	h.i.i.InstallUncaughtExceptionHandler#handleException: Caught unhandled exception with ID XXXXXXXXXXXXXXXXXXXXXXXXXX
org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"typ":"JWT","alg":"RS256","kid":"_XXXXXXXXXXXXXXXXXXXXXXX"}

**Comment by timja** [comment] 2022-05-12 21:05
Looks to be a duplicate of this https://github.com/jenkinsci/azure-ad-plugin/issues/33#issuecomment-514570020

Take a look at the fix there

**Comment by timja** [comment] 2023-12-19 16:45
Fixed with https://github.com/jenkinsci/azure-ad-plugin/pull/455

**Closed by timja** 2023-12-19 16:45 UTC
Labels: bug
