### ISSUE TITLE
Support for Sovernign Clouds

### ISSUE THREAD

**Issue by KevinDMack** [jenkinsci/azure-ad-plugin#78] opened 2020-06-11 15:56 UTC
Currently this plugin has a hardcoding value for https://login.windows.net, which is preventing it from working with any sovernign cloud, can this be made into a configurable variable?

**Comment by timja** [comment] 2021-04-07 20:02
Duplicate of https://github.com/jenkinsci/azure-ad-plugin/issues/60

**Closed by timja** 2021-04-07 20:02 UTC
